spring.application.name=2d-game

# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:gamedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console at /h2-console
spring.h2.console.enabled=true

# SpringDoc / Swagger UI at /swagger-ui/index.html
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
